import { useEffect, useMemo, useState } from "react";
import { WorkDrawer } from "../../components/work-drawer";
import { StatusBadge } from "../../components/status-badge";
import { shortDate } from "../../lib/format";
import { classifyCorrespondence, openCorrespondenceDocument, transitionCorrespondence } from "./repository";
import type { MailroomInboxItem, MailroomReferenceData } from "./types";

type AnyRow = Record<string, any> & { id: string };
const correspondenceTypes = ["eob", "denial_letter", "appeal", "reconsideration", "recoupment_notice", "refund_request", "credentialing_letter", "medical_record_request", "prior_authorization_notice", "payer_correspondence", "general_correspondence"] as const;
function humanize(value: unknown) { return String(value ?? "").replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function personName(row?: AnyRow | null) { return row ? [row.first_name, row.last_name].filter(Boolean).join(" ") || "—" : "—"; }
function formFor(row: MailroomInboxItem) { return { subject: row.subject, correspondenceType: row.correspondence_type, payerId: row.payer_id ?? "", clientId: row.client_id ?? "", claimId: row.claim_id ?? "", providerId: row.provider_id ?? "", assignedUserId: row.assigned_user_id ?? "", dueDate: row.due_date ?? "", notes: row.notes ?? "" }; }

export function MailroomWorkDrawer({ open, onOpenChange, row, refs, queuePosition, onPrevious, onNext, previousDisabled, nextDisabled, onSaved }: { open: boolean; onOpenChange: (open: boolean) => void; row: MailroomInboxItem | null; refs: MailroomReferenceData | null; queuePosition?: string; onPrevious?: () => void; onNext?: () => void; previousDisabled?: boolean; nextDisabled?: boolean; onSaved: () => Promise<void> | void }) {
  const [form, setForm] = useState<ReturnType<typeof formFor> | null>(null); const [baseline, setBaseline] = useState<ReturnType<typeof formFor> | null>(null); const [saving, setSaving] = useState(false); const [reason, setReason] = useState(""); const [error, setError] = useState<string | null>(null);
  useEffect(() => { if (!open || !row) return; const next = formFor(row); setForm(next); setBaseline({ ...next }); setReason(""); setError(null); }, [open, row?.id]);
  const dirty = useMemo(() => Boolean(form && baseline && JSON.stringify(form) !== JSON.stringify(baseline)), [form, baseline]);
  if (!row || !refs || !form) return null;
  const activeRow = row; const activeRefs = refs; const activeForm = form;
  const clients = activeRefs.clients as AnyRow[]; const providers = activeRefs.providers as AnyRow[]; const payers = activeRefs.payers as AnyRow[]; const claims = activeRefs.claims as AnyRow[]; const filteredClaims = activeForm.clientId ? claims.filter((claim) => String(claim.client_id ?? "") === activeForm.clientId) : claims;
  async function save() { if (!activeForm.subject.trim()) { setError("Subject is required."); return; } setSaving(true); setError(null); try { await classifyCorrespondence(activeRow.id, { subject: activeForm.subject.trim(), correspondenceType: activeForm.correspondenceType, payerId: activeForm.payerId || null, clientId: activeForm.clientId || null, claimId: activeForm.claimId || null, providerId: activeForm.providerId || null, authorizationId: activeRow.authorization_id ?? null, appealId: activeRow.appeal_id ?? null, assignedUserId: activeForm.assignedUserId || null, dueDate: activeForm.dueDate || null, notes: activeForm.notes.trim() || null }); setBaseline({ ...activeForm }); await onSaved(); } catch (err) { setError(err instanceof Error ? err.message : "Unable to save correspondence."); } finally { setSaving(false); } }
  async function transition(action: "review" | "require_action" | "start" | "pend" | "resolve" | "close" | "reopen", label: string) { if (["pend", "resolve", "close", "reopen"].includes(action) && !reason.trim()) { setError(`Enter a note before ${label.toLowerCase()}.`); return; } setSaving(true); setError(null); try { await transitionCorrespondence(activeRow.id, action, reason.trim() || `${label} from Mailroom work drawer.`); setReason(""); await onSaved(); } catch (err) { setError(err instanceof Error ? err.message : "Unable to update correspondence."); } finally { setSaving(false); } }
  async function openDocument() { const path = String((activeRow.document as AnyRow | null)?.storage_path ?? ""); if (!path) { setError("No stored document is linked to this correspondence."); return; } try { const url = await openCorrespondenceDocument(path, 300); window.open(url, "_blank", "noopener,noreferrer"); } catch (err) { setError(err instanceof Error ? err.message : "Unable to open document."); } }
  const footer = <div className="thera-filter-row" style={{ justifyContent: "space-between" }}><button type="button" className="thera-action secondary" onClick={() => onOpenChange(false)}>Close</button><div className="thera-filter-row"><button type="button" className="thera-action secondary" disabled={saving || !dirty} onClick={() => void save()}>Save</button><button type="button" className="thera-action" disabled={saving || nextDisabled} onClick={() => { void (async () => { if (dirty) await save(); onNext?.(); })(); }}>Save & Continue</button></div></div>;
  return <WorkDrawer open={open} onOpenChange={onOpenChange} dirty={dirty} title={activeRow.subject} subtitle={`${activeRow.payerName} · ${activeRow.patientName} · Received ${shortDate(activeRow.receivedDate)}`} badges={<StatusBadge value={String(activeRow.status)} />} queuePosition={queuePosition} onPrevious={onPrevious} onNext={onNext} previousDisabled={previousDisabled} nextDisabled={nextDisabled} openFullRecord={() => { window.location.href = `/mailroom/${activeRow.id}`; }} openFullRecordLabel="Open Full Correspondence" footer={footer}>
    {error && <div className="thera-state error" style={{ marginBottom: 12 }}>{error}</div>}
    <section className="thera-card"><div className="thera-card-header"><div><h2>Correspondence</h2><p>Review the item while keeping the inbox and filters in place.</p></div>{Boolean(activeRow.document) && <button type="button" className="thera-action secondary" onClick={() => void openDocument()}>View Document</button>}</div><div className="thera-form-grid"><div><div className="thera-table-subtext">Type</div><strong>{humanize(activeRow.correspondenceType)}</strong></div><div><div className="thera-table-subtext">Due</div><strong>{activeRow.dueDate ? shortDate(activeRow.dueDate) : "—"}</strong></div><div><div className="thera-table-subtext">Claim</div><strong>{activeRow.claimNumber}</strong></div><div><div className="thera-table-subtext">Provider</div><strong>{activeRow.providerName}</strong></div></div></section>
    <section className="thera-card"><h2>Classification and links</h2><div className="thera-form-grid"><label>Subject<input className="thera-input" value={activeForm.subject} onChange={(e) => setForm({ ...activeForm, subject: e.target.value })} /></label><label>Classification<select className="thera-select" value={activeForm.correspondenceType} onChange={(e) => setForm({ ...activeForm, correspondenceType: e.target.value })}>{correspondenceTypes.map((value) => <option key={value} value={value}>{humanize(value)}</option>)}</select></label><label>Link to payer<select className="thera-select" value={activeForm.payerId} onChange={(e) => setForm({ ...activeForm, payerId: e.target.value })}><option value="">No payer</option>{payers.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Link to patient<select className="thera-select" value={activeForm.clientId} onChange={(e) => setForm({ ...activeForm, clientId: e.target.value, claimId: "" })}><option value="">No patient</option>{clients.map((item) => <option key={item.id} value={item.id}>{personName(item)}</option>)}</select></label><label>Link to claim<select className="thera-select" value={activeForm.claimId} onChange={(e) => setForm({ ...activeForm, claimId: e.target.value })}><option value="">No claim</option>{filteredClaims.map((item) => <option key={item.id} value={item.id}>{item.patient_control_number || item.payer_claim_number || "Claim"}</option>)}</select></label><label>Link to provider<select className="thera-select" value={activeForm.providerId} onChange={(e) => setForm({ ...activeForm, providerId: e.target.value })}><option value="">No provider</option>{providers.map((item) => <option key={item.id} value={item.id}>{personName(item)}{item.credentials ? `, ${item.credentials}` : ""}</option>)}</select></label><label>Due date<input className="thera-input" type="date" value={activeForm.dueDate} onChange={(e) => setForm({ ...activeForm, dueDate: e.target.value })} /></label><label>Assignee<select className="thera-select" value={activeForm.assignedUserId} onChange={(e) => setForm({ ...activeForm, assignedUserId: e.target.value })}><option value="">Unassigned</option>{activeRefs.assignees.map((item) => <option key={item.user_id} value={item.user_id}>{item.display_label}</option>)}</select></label><label style={{ gridColumn: "1 / -1" }}>Notes<textarea className="thera-input" rows={5} value={activeForm.notes} onChange={(e) => setForm({ ...activeForm, notes: e.target.value })} /></label></div></section>
    <section className="thera-card"><h2>Workflow</h2><label>Activity note<textarea className="thera-input" rows={3} value={reason} onChange={(e) => setReason(e.target.value)} placeholder="Add context for the workflow action" /></label><div className="thera-filter-row" style={{ marginTop: 12 }}><button type="button" className="thera-action secondary" disabled={saving} onClick={() => void transition("review", "Mark Reviewed")}>Mark Reviewed</button><button type="button" className="thera-action secondary" disabled={saving} onClick={() => void transition("require_action", "Create Work Item")}>Create Work Item</button><button type="button" className="thera-action secondary" disabled={saving} onClick={() => void transition("start", "Start Work")}>Start Work</button><button type="button" className="thera-action" disabled={saving} onClick={() => void transition("resolve", "Mark Complete")}>Mark Complete</button></div></section>
  </WorkDrawer>;
}
