import { useEffect, useMemo, useState } from "react";
import { WorkDrawer } from "../../components/work-drawer";
import { StatusBadge } from "../../components/status-badge";
import { money, shortDate } from "../../lib/format";
import type { AppealWorkspaceRow, ArRow, DenialWorkspaceRow, RecoveryWorkspaceRow, VarianceWorkspaceRow } from "./repository";

type CommonProps = { open: boolean; onOpenChange: (open: boolean) => void; saving?: boolean };
type DenialDetail = DenialWorkspaceRow & { serviceDate?: string; providerName?: string; claimStatus?: string; chargeAmountCents?: number };
function value(input: unknown, fallback = "—") { return input == null || input === "" ? fallback : String(input); }
function ContextGrid({ children }: { children: React.ReactNode }) { return <div className="thera-form-grid" style={{ marginBottom: 16 }}>{children}</div>; }
function Fact({ label, children }: { label: string; children: React.ReactNode }) { return <div><div className="thera-table-subtext">{label}</div><strong>{children}</strong></div>; }

export function WorkDenialDrawer({ open, onOpenChange, row, saving, onStartWork, onCreateAppeal, onWriteOff }: CommonProps & { row: DenialWorkspaceRow | null; onStartWork: (row: DenialWorkspaceRow) => void; onCreateAppeal: (row: DenialWorkspaceRow) => void; onWriteOff: (row: DenialWorkspaceRow) => void }) {
  if (!row) return null; const detail = row as DenialDetail;
  const footer = <div className="thera-filter-row" style={{ justifyContent: "space-between" }}><button type="button" className="thera-action secondary" onClick={() => onOpenChange(false)}>Close</button><div className="thera-filter-row">{row.policy === "auto_writeoff" ? <button type="button" className="thera-action" disabled={saving || row.denial_status === "resolved_writeoff"} onClick={() => onWriteOff(row)}>Write Off</button> : <><button type="button" className="thera-action secondary" disabled={saving} onClick={() => onStartWork(row)}>Start Follow-Up</button><button type="button" className="thera-action" disabled={saving || Boolean(row.activeAppealId)} onClick={() => onCreateAppeal(row)}>{row.activeAppealId ? "Appeal Active" : "Create Appeal"}</button></>}</div></div>;
  return <WorkDrawer open={open} onOpenChange={onOpenChange} title={row.clientName} subtitle={`${row.claimNumber} · ${row.payerName}`} badges={<><StatusBadge value={value(row.denial_status, "new")} /><StatusBadge value={value(row.workability ?? row.policy)} /></>} openFullRecord={row.claim_id ? () => { window.location.href = `/claims/${String(row.claim_id)}`; } : undefined} openFullRecordLabel="Open Full Claim 360" footer={footer}>
    <ContextGrid><Fact label="Patient">{row.clientName}</Fact><Fact label="Claim">{row.claimNumber}</Fact><Fact label="Payer">{row.payerName}</Fact><Fact label="DOS">{detail.serviceDate ? shortDate(detail.serviceDate) : "—"}</Fact><Fact label="Denied amount">{money(Number(row.amount_cents ?? 0))}</Fact><Fact label="CARC">{value(row.carc_code)}</Fact><Fact label="RARC">{value(row.rarc_code)}</Fact><Fact label="Denial category">{value(row.denial_category, "other").replaceAll("_", " ")}</Fact><Fact label="Workability">{value(row.workability ?? row.policy)}</Fact><Fact label="Appeal deadline">{row.timely_filing_deadline ? shortDate(String(row.timely_filing_deadline)) : "—"}</Fact></ContextGrid>
    <section className="thera-card"><h2>Denial reason</h2><p>{value(row.reason, "No denial reason recorded.")}</p></section>
    <section className="thera-card"><h2>Related claim information</h2><ContextGrid><Fact label="Rendering provider">{value(detail.providerName)}</Fact><Fact label="Claim status">{value(detail.claimStatus)}</Fact><Fact label="Charge amount">{detail.chargeAmountCents == null ? "—" : money(detail.chargeAmountCents)}</Fact></ContextGrid></section>
    <section className="thera-card"><h2>Existing notes / activity</h2><p>{value(row.notes, "No denial notes recorded.")}</p></section>
  </WorkDrawer>;
}

export function CreateAppealDrawer({ open, onOpenChange, row, saving, onSave }: CommonProps & { row: DenialWorkspaceRow | null; onSave: (row: DenialWorkspaceRow, level: number, deadline: string, notes: string) => Promise<void> | void }) {
  const [level, setLevel] = useState("1"); const [deadline, setDeadline] = useState(""); const [notes, setNotes] = useState("");
  useEffect(() => { if (!open || !row) return; setLevel("1"); setDeadline(String(row.timely_filing_deadline ?? "").slice(0, 10)); setNotes(String(row.reason ?? "")); }, [open, row?.id]);
  const dirty = useMemo(() => Boolean(row) && (level !== "1" || deadline !== String(row?.timely_filing_deadline ?? "").slice(0, 10) || notes !== String(row?.reason ?? "")), [row, level, deadline, notes]);
  if (!row) return null;
  const footer = <div className="thera-filter-row" style={{ justifyContent: "space-between" }}><button type="button" className="thera-action secondary" onClick={() => onOpenChange(false)}>Cancel</button><button type="button" className="thera-action" disabled={saving || !deadline || Number(level) < 1} onClick={() => void onSave(row, Number(level), deadline, notes)}>Create Appeal</button></div>;
  return <WorkDrawer open={open} onOpenChange={onOpenChange} dirty={dirty} title="Create Appeal" subtitle={`${row.clientName} · ${row.claimNumber} · ${row.payerName}`} footer={footer}>
    <ContextGrid><Fact label="CARC">{value(row.carc_code)}</Fact><Fact label="RARC">{value(row.rarc_code)}</Fact><Fact label="Denied amount">{money(Number(row.amount_cents ?? 0))}</Fact><Fact label="Workability">{value(row.workability ?? row.policy)}</Fact></ContextGrid>
    <div className="thera-form-grid"><label>Appeal level<select className="thera-input" value={level} onChange={(e) => setLevel(e.target.value)}><option value="1">Level 1</option><option value="2">Level 2</option><option value="3">Level 3</option></select></label><label>Appeal deadline<input className="thera-input" type="date" value={deadline} onChange={(e) => setDeadline(e.target.value)} /></label><label style={{ gridColumn: "1 / -1" }}>Notes<textarea className="thera-input" rows={7} value={notes} onChange={(e) => setNotes(e.target.value)} /></label></div>
  </WorkDrawer>;
}

export function AppealOutcomeDrawer({ open, onOpenChange, row, saving, onSave }: CommonProps & { row: AppealWorkspaceRow | null; onSave: (row: AppealWorkspaceRow, outcome: "approved" | "partially_approved" | "denied" | "withdrawn", notes: string) => Promise<void> | void }) {
  const [outcome, setOutcome] = useState<"approved" | "partially_approved" | "denied" | "withdrawn">("approved"); const [notes, setNotes] = useState("");
  useEffect(() => { if (!open || !row) return; setOutcome("approved"); setNotes(String(row.notes ?? "")); }, [open, row?.id]);
  const dirty = Boolean(row) && (outcome !== "approved" || notes !== String(row?.notes ?? ""));
  if (!row) return null;
  const footer = <div className="thera-filter-row" style={{ justifyContent: "space-between" }}><button type="button" className="thera-action secondary" onClick={() => onOpenChange(false)}>Cancel</button><button type="button" className="thera-action" disabled={saving} onClick={() => void onSave(row, outcome, notes)}>Record Outcome</button></div>;
  return <WorkDrawer open={open} onOpenChange={onOpenChange} dirty={dirty} title="Record Appeal Outcome" subtitle={`${row.clientName} · ${row.claimNumber} · ${row.payerName}`} footer={footer}>
    <ContextGrid><Fact label="Appeal level">{value(row.appeal_level)}</Fact><Fact label="Status">{value(row.appeal_status)}</Fact><Fact label="Due">{row.deadline_date ? shortDate(String(row.deadline_date)) : "—"}</Fact><Fact label="Submitted">{row.submitted_at ? shortDate(String(row.submitted_at)) : "—"}</Fact></ContextGrid>
    <div className="thera-form-grid"><label>Outcome<select className="thera-input" value={outcome} onChange={(e) => setOutcome(e.target.value as typeof outcome)}><option value="approved">Approved</option><option value="partially_approved">Partially approved</option><option value="denied">Denied / upheld</option><option value="withdrawn">Withdrawn</option></select></label><label style={{ gridColumn: "1 / -1" }}>Notes<textarea className="thera-input" rows={7} value={notes} onChange={(e) => setNotes(e.target.value)} /></label></div>
  </WorkDrawer>;
}

export function UnderpaymentReviewDrawer({ open, onOpenChange, row, saving, onRoute }: CommonProps & { row: VarianceWorkspaceRow | null; onRoute: (row: VarianceWorkspaceRow) => void }) { if (!row) return null; return <WorkDrawer open={open} onOpenChange={onOpenChange} title="Underpayment Review" subtitle={`${row.clientName} · ${row.claimNumber} · ${row.payerName}`} badges={<StatusBadge value={row.workStatus} />} openFullRecord={() => { window.location.href = `/claims/${row.id}`; }} openFullRecordLabel="Open Full Claim 360" footer={<div className="thera-filter-row" style={{ justifyContent: "space-between" }}><button className="thera-action secondary" type="button" onClick={() => onOpenChange(false)}>Close</button><button className="thera-action" type="button" disabled={saving || Boolean(row.workItemId)} onClick={() => onRoute(row)}>{row.workItemId ? "Already Routed" : "Create Follow-Up"}</button></div>}><ContextGrid><Fact label="Patient">{row.clientName}</Fact><Fact label="Payer">{row.payerName}</Fact><Fact label="Provider">{row.providerName}</Fact><Fact label="DOS">{shortDate(row.serviceDate)}</Fact><Fact label="Expected allowed">{money(row.expectedAllowedCents)}</Fact><Fact label="Actual allowed">{money(row.actualAllowedCents)}</Fact><Fact label="Underpayment">{money(row.varianceCents)}</Fact><Fact label="Matched lines">{row.matchedLineCount}</Fact></ContextGrid></WorkDrawer>; }

export function RecoveryReviewDrawer({ open, onOpenChange, row, saving, onRoute }: CommonProps & { row: RecoveryWorkspaceRow | null; onRoute: (row: RecoveryWorkspaceRow) => void }) { if (!row) return null; const kind = String(row.adjustment_type ?? "recovery").replaceAll("_", " "); return <WorkDrawer open={open} onOpenChange={onOpenChange} title={kind.includes("refund") ? "Refund Review" : "Recoupment Review"} subtitle={`${row.clientName} · ${row.claimNumber} · ${row.payerName}`} badges={<StatusBadge value={row.workStatus} />} openFullRecord={row.claim_id ? () => { window.location.href = `/claims/${String(row.claim_id)}`; } : undefined} openFullRecordLabel="Open Full Claim 360" footer={<div className="thera-filter-row" style={{ justifyContent: "space-between" }}><button className="thera-action secondary" type="button" onClick={() => onOpenChange(false)}>Close</button><button className="thera-action" type="button" disabled={saving || Boolean(row.workItemId)} onClick={() => onRoute(row)}>{row.workItemId ? "Already Routed" : "Create Follow-Up"}</button></div>}><ContextGrid><Fact label="Patient">{row.clientName}</Fact><Fact label="Payer">{row.payerName}</Fact><Fact label="Adjustment type">{kind}</Fact><Fact label="Amount">{money(Number(row.amount_cents ?? 0))}</Fact><Fact label="Status">{value(row.adjustment_status)}</Fact><Fact label="Reason">{value(row.reason)}</Fact></ContextGrid></WorkDrawer>; }

export function FollowUpActivityDrawer({ open, onOpenChange, row }: CommonProps & { row: ArRow | null }) { if (!row) return null; return <WorkDrawer open={open} onOpenChange={onOpenChange} title="Follow-Up Activity" subtitle={`${row.clientName} · ${value(row.patient_control_number)} · ${row.payerName}`} openFullRecord={() => { window.location.href = `/claims/${row.id}`; }} openFullRecordLabel="Open Full Claim 360" footer={<button type="button" className="thera-action secondary" onClick={() => onOpenChange(false)}>Close</button>}><ContextGrid><Fact label="Patient">{row.clientName}</Fact><Fact label="Payer">{row.payerName}</Fact><Fact label="Provider">{row.providerName}</Fact><Fact label="Open balance">{money(row.openBalanceCents)}</Fact><Fact label="Aging">{row.daysOutstanding} days · {row.bucket}</Fact><Fact label="Work status">{row.workStatus}</Fact></ContextGrid></WorkDrawer>; }
