import { useEffect,useMemo,useState } from "react";
import { useRoute } from "wouter";
import { crmApi, getCrmDocumentDownloadUrl, uploadCrmDocument } from "./crm-api";
import { buildCallScript } from "./call-script";
import { PaymentPanel } from "./PaymentPanel";
import { PaymentLinkPanel } from "./PaymentLinkPanel";
import { PaymentPlanEditor } from "./PaymentPlanEditor";
import { downloadPaymentPlanAgreement } from "./agreement-pdf";
import type { CrmAccount,CrmActivity,CrmCall,CrmDocument,CrmNote,CrmPlanBundle } from "./types";

const money=(c:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(c/100);
const sections=["Overview","Payment Plan","Calls","Documents","Payments","Notes","Activity"] as const;
type Section=typeof sections[number];

export function AccountDetailPage(){
 const [,params]=useRoute<{id:string}>("/crm/accounts/:id");const accountId=params?.id||"";
 const [account,setAccount]=useState<CrmAccount|null>(null);const [calls,setCalls]=useState<CrmCall[]>([]);const [notes,setNotes]=useState<CrmNote[]>([]);const [docs,setDocs]=useState<CrmDocument[]>([]);const [activity,setActivity]=useState<CrmActivity[]>([]);const [plan,setPlan]=useState<CrmPlanBundle>({plan:null,installments:[]});
 const [section,setSection]=useState<Section>("Overview");const [panel,setPanel]=useState<"call"|"script"|"payment"|"link"|"document"|"plan"|null>(null);const [error,setError]=useState<string|null>(null);
 const [call,setCall]=useState({direction:"outbound",disposition:"follow_up_needed",notes:"",promiseToPay:"",promiseDate:"",followUp:""});
 const [note,setNote]=useState("");
 const [docFile,setDocFile]=useState<File|null>(null);const [docCategory,setDocCategory]=useState("other");const [docBusy,setDocBusy]=useState(false);
 const load=async()=>{try{const [a,c,n,d,x,p]=await Promise.all([crmApi<{account:CrmAccount}>("account",{query:{accountId}}),crmApi<{calls:CrmCall[]}>("calls",{query:{accountId}}),crmApi<{notes:CrmNote[]}>("notes",{query:{accountId}}),crmApi<{documents:CrmDocument[]}>("documents",{query:{accountId}}),crmApi<{activity:CrmActivity[]}>("activity",{query:{accountId}}),crmApi<CrmPlanBundle>("plan",{query:{accountId}})]);setAccount(a.account);setCalls(c.calls);setNotes(n.notes);setDocs(d.documents);setActivity(x.activity);setPlan(p);setError(null);}catch(e){setError(e instanceof Error?e.message:"Unable to load account.");}};
 useEffect(()=>{if(accountId)void load();},[accountId]);
 const script=useMemo(()=>account?buildCallScript(account,plan.plan):[],[account,plan.plan]);
 if(!account)return <section className="crm-stack">{error?<div className="crm-alert">{error}</div>:<div className="crm-card">Loading account...</div>}</section>;
 async function logCall(e:React.FormEvent){e.preventDefault();await crmApi("create-call",{method:"POST",body:{accountId,direction:call.direction,disposition:call.disposition,notes:call.notes,promiseToPayCents:call.promiseToPay?Math.round(Number(call.promiseToPay)*100):null,promiseToPayDate:call.promiseDate||null,nextFollowUpAt:call.followUp?new Date(call.followUp).toISOString():null}});setPanel(null);setCall({direction:"outbound",disposition:"follow_up_needed",notes:"",promiseToPay:"",promiseDate:"",followUp:""});await load();}
 async function addNote(e:React.FormEvent){e.preventDefault();if(!note.trim())return;await crmApi("create-note",{method:"POST",body:{accountId,note}});setNote("");await load();}
 async function uploadDocument(e:React.FormEvent){e.preventDefault();if(!docFile)return;setDocBusy(true);try{await uploadCrmDocument({accountId,file:docFile,category:docCategory});setDocFile(null);setDocCategory("other");setPanel(null);setSection("Documents");await load();}catch(err){setError(err instanceof Error?err.message:"Unable to upload document.");}finally{setDocBusy(false);}}
 async function openDocument(documentId:string){try{const signedUrl=await getCrmDocumentDownloadUrl(documentId);window.open(signedUrl,"_blank","noopener,noreferrer");}catch(err){setError(err instanceof Error?err.message:"Unable to open document.");}}
 async function generateAgreement(){if(!account||!plan.plan)return;try{downloadPaymentPlanAgreement(account,plan.plan,plan.installments);await crmApi("set-agreement-status",{method:"POST",body:{planId:plan.plan.id,agreementStatus:"generated"}});await load();}catch(err){setError(err instanceof Error?err.message:"Unable to generate agreement.");}}
 async function setAgreementStatus(status:"sent"|"declined"){if(!plan.plan)return;try{await crmApi("set-agreement-status",{method:"POST",body:{planId:plan.plan.id,agreementStatus:status}});await load();}catch(err){setError(err instanceof Error?err.message:"Unable to update agreement status.");}}
 function openSignedAgreementUpload(){setDocCategory("signed_payment_plan_agreement");setSection("Documents");setPanel("document");}
 return <section className="crm-stack">
  <div className="crm-page-head"><div><div className="crm-muted">Account {account.account_number}</div><h1>{account.customer_name}</h1></div><span className={"crm-status "+account.status}>{account.status.replace("_"," ")}</span></div>
  {error&&<div className="crm-alert">{error}</div>}
  <div className="crm-summary-grid"><div className="crm-card"><span>Current balance</span><strong>{money(account.currentBalanceCents)}</strong></div><div className="crm-card"><span>Original balance</span><strong>{money(account.originalBalanceCents)}</strong></div><div className="crm-card"><span>Next follow-up</span><strong>{account.next_follow_up_at?new Date(account.next_follow_up_at).toLocaleDateString():"Not set"}</strong></div></div>
  <div className="crm-quick-actions"><button className="crm-primary" onClick={()=>setPanel("payment")}>Take Payment</button><button onClick={()=>setPanel("link")}>Text Payment Link</button><button onClick={()=>setPanel("call")}>Log Call</button><button onClick={()=>{setSection("Documents");setPanel("document")}}>Add Document</button><button onClick={()=>setPanel("script")}>Help / Call Script</button></div>
  <div className="crm-tabs">{sections.map(s=><button key={s} className={section===s?"active":""} onClick={()=>setSection(s)}>{s}</button>)}</div>
  {section==="Overview"&&<div className="crm-card crm-detail-grid"><div><span className="crm-label">Phone</span><div>{account.phone||"—"}</div></div><div><span className="crm-label">Email</span><div>{account.email||"—"}</div></div><div><span className="crm-label">Address</span><div>{[account.address_line1,account.address_line2,account.city,account.state,account.postal_code].filter(Boolean).join(", ")||"—"}</div></div></div>}
  {section==="Payment Plan"&&<div className="crm-stack">
    <div className="crm-card">{plan.plan?<><div className="crm-row-between"><div><strong>{plan.plan.status.toUpperCase()} PLAN</strong><div className="crm-muted">Agreement: {plan.plan.agreement_status.replaceAll("_"," ")} · version {Math.max(1,plan.plan.agreement_version||1)}</div></div><span>{money(plan.plan.installment_cents)} · {plan.plan.frequency}</span></div><div className="crm-plan-actions"><button onClick={()=>setPanel("plan")}>Modify Plan</button><button className="crm-primary" onClick={()=>void generateAgreement()}>Generate / Download Agreement</button><button onClick={()=>void setAgreementStatus("sent")}>Mark Agreement Sent</button><button onClick={openSignedAgreementUpload}>Upload Signed Agreement</button><button onClick={()=>void setAgreementStatus("declined")}>Mark Declined</button></div><div className="crm-installments">{plan.installments.map(i=><div key={i.id} className="crm-installment"><span>#{i.sequence_number} · {new Date(i.due_date+"T00:00:00").toLocaleDateString()}</span><strong>{money(i.amount_due_cents)}</strong><span className="crm-muted">{i.status}</span></div>)}</div></>:<><p>No payment plan has been created.</p><button className="crm-primary" onClick={()=>setPanel("plan")}>Create Payment Plan</button></>}</div>
  </div>}
  {section==="Calls"&&<div className="crm-stack">{calls.map(c=><div className="crm-card" key={c.id}><div className="crm-row-between"><strong>{c.direction} · {c.disposition.replaceAll("_"," ")}</strong><span className="crm-muted">{new Date(c.created_at).toLocaleString()}</span></div>{c.notes&&<p>{c.notes}</p>}<div className="crm-muted">Logged by {c.created_by}</div></div>)}</div>}
  {section==="Documents"&&<div className="crm-stack">{docs.map(d=><div className="crm-card crm-row-between" key={d.id}><div><strong>{d.display_name}</strong><div className="crm-muted">{d.category.replaceAll("_"," ")} · {new Date(d.uploaded_at).toLocaleDateString()}</div></div><button onClick={()=>void openDocument(d.id)}>Open</button></div>)}{!docs.length&&<div className="crm-card crm-empty">No documents uploaded.</div>}</div>}
  {section==="Payments"&&<div className="crm-stack">{(account.payments||[]).map(p=><div key={p.id} className="crm-card crm-row-between"><div><strong>{money(p.amount_cents)}</strong><div className="crm-muted">{new Date(p.created_at).toLocaleString()} · {p.card_brand||"Card"} {p.card_last4?"•••• "+p.card_last4:""}{p.square_environment==="sandbox"?" · Sandbox test":""}</div></div><span className={"crm-status "+p.square_status.toLowerCase()}>{p.square_status}</span></div>)}{!(account.payments||[]).length&&<div className="crm-card crm-empty">No linked payments.</div>}</div>}
  {section==="Notes"&&<div className="crm-stack"><form className="crm-card crm-note-form" onSubmit={addNote}><textarea placeholder="Add account note" value={note} onChange={e=>setNote(e.target.value)}/><button className="crm-primary">Add Note</button></form>{notes.map(n=><div key={n.id} className="crm-card"><p>{n.note}</p><div className="crm-muted">{n.created_by} · {new Date(n.created_at).toLocaleString()}</div></div>)}</div>}
  {section==="Activity"&&<div className="crm-timeline">{activity.map(a=><div key={a.id} className="crm-activity"><div className="crm-dot"/><div><strong>{a.summary}</strong><div className="crm-muted">{a.actor_email} · {new Date(a.created_at).toLocaleString()}</div></div></div>)}</div>}
  {panel==="call"&&<div className="crm-modal-backdrop"><form className="crm-modal" onSubmit={logCall}><div className="crm-row-between"><h2>Log Call</h2><button type="button" onClick={()=>setPanel(null)}>Close</button></div><label>Direction<select value={call.direction} onChange={e=>setCall({...call,direction:e.target.value})}><option value="outbound">Outbound</option><option value="inbound">Inbound</option></select></label><label>Outcome<select value={call.disposition} onChange={e=>setCall({...call,disposition:e.target.value})}><option value="paid">Paid</option><option value="payment_plan_discussed">Payment Plan Discussed</option><option value="promise_to_pay">Promise to Pay</option><option value="no_answer">No Answer</option><option value="left_voicemail">Left Voicemail</option><option value="follow_up_needed">Follow-Up Needed</option><option value="dispute_question">Dispute / Question</option><option value="other">Other</option></select></label><label>Notes<textarea value={call.notes} onChange={e=>setCall({...call,notes:e.target.value})}/></label><label>Promise amount<input inputMode="decimal" value={call.promiseToPay} onChange={e=>setCall({...call,promiseToPay:e.target.value})}/></label><label>Promise date<input type="date" value={call.promiseDate} onChange={e=>setCall({...call,promiseDate:e.target.value})}/></label><label>Next follow-up<input type="datetime-local" value={call.followUp} onChange={e=>setCall({...call,followUp:e.target.value})}/></label><button className="crm-primary">Save Call</button></form></div>}
  {panel==="script"&&<div className="crm-modal-backdrop"><div className="crm-modal crm-script"><div className="crm-row-between"><h2>Help / Call Script</h2><button onClick={()=>setPanel(null)}>Close</button></div>{script.map(s=><section key={s.title}><h3>{s.title}</h3><p>{s.body}</p></section>)}</div></div>}
  {panel==="document"&&<div className="crm-modal-backdrop"><form className="crm-modal" onSubmit={uploadDocument}><div className="crm-row-between"><h2>Add Document</h2><button type="button" onClick={()=>setPanel(null)}>Close</button></div><label>Category<select value={docCategory} onChange={e=>setDocCategory(e.target.value)}><option value="invoice">Invoice</option><option value="contract">Contract</option><option value="correspondence">Correspondence</option><option value="collection_notice">Collection Notice</option><option value="payment_plan_agreement">Payment Plan Agreement</option><option value="signed_payment_plan_agreement">Signed Payment Plan Agreement</option><option value="other">Other</option></select></label><label>File<input required type="file" accept=".pdf,.doc,.docx,image/jpeg,image/png,image/webp,text/plain" onChange={e=>setDocFile(e.target.files?.[0]||null)}/></label><div className="crm-muted">Maximum file size: 20 MB. Documents are stored privately.</div><button className="crm-primary" disabled={!docFile||docBusy}>{docBusy?"Uploading…":"Upload Document"}</button></form></div>}
{panel==="plan"&&<PaymentPlanEditor account={account} bundle={plan} onClose={()=>setPanel(null)} onSaved={async()=>{await load();}}/>}
{panel==="payment"&&<PaymentPanel account={account} plan={plan} onClose={()=>setPanel(null)} onComplete={async()=>{setPanel(null);await load();}}/>}
  {panel==="link"&&<PaymentLinkPanel account={account} plan={plan} onClose={()=>setPanel(null)} onComplete={async()=>{await load();}}/>}
 </section>;
}
