import { useEffect,useRef,useState } from "react";
import { CrmApiError, paymentDeskApi } from "./crm-api";
import type { CrmAccount, CrmPlanBundle } from "./types";

declare global { interface Window { Square?: any; } }

type SquareConfig={configured:boolean;environment:"production"|"sandbox";applicationId:string;locationId:string;scriptUrl:string};
type MeResponse={user:{must_change_password?:boolean};square:SquareConfig};

async function loadSquareScript(src:string){
  const existing=[...document.scripts].find(s=>s.src===src);
  if(existing){if(window.Square)return;await new Promise<void>((resolve,reject)=>{existing.addEventListener("load",()=>resolve(),{once:true});existing.addEventListener("error",()=>reject(new Error("Unable to load Square secure payment fields.")),{once:true});});return;}
  await new Promise<void>((resolve,reject)=>{const script=document.createElement("script");script.src=src;script.async=true;script.onload=()=>resolve();script.onerror=()=>reject(new Error("Unable to load Square secure payment fields."));document.head.appendChild(script);});
}

export function PaymentPanel({account,plan,onClose,onComplete}:{account:CrmAccount;plan:CrmPlanBundle;onClose():void;onComplete():Promise<void>|void}){
 const cardRef=useRef<any>(null);const idemRef=useRef<string|null>(null);
 const [amount,setAmount]=useState((account.currentBalanceCents/100).toFixed(2));const [reference]=useState(account.account_number);const [note,setNote]=useState("");
 const [billing,setBilling]=useState({first:"",last:"",email:account.email||"",phone:account.phone||"",address:"",city:"",state:"CO",zip:""});
 const [message,setMessage]=useState("Loading secure card fields…");const [busy,setBusy]=useState(false);const [ready,setReady]=useState(false);
 const nextInstallment=plan.installments.find(i=>i.status!=="paid"&&i.status!=="waived");
 useEffect(()=>{let active=true;let card:any=null;(async()=>{try{if(!window.isSecureContext)throw new Error("Secure HTTPS is required for card entry.");const me=await paymentDeskApi<MeResponse>("me");if(!me.square.configured)throw new Error("Square is not connected.");if(me.user.must_change_password)throw new Error("Change the temporary password before taking a payment.");await loadSquareScript(me.square.scriptUrl);if(!window.Square)throw new Error("Square secure fields did not initialize.");const payments=window.Square.payments(me.square.applicationId,me.square.locationId);card=await payments.card();if(!active){await card.destroy();return;}cardRef.current=card;await card.attach("#crm-square-card");if(active){setReady(true);setMessage("Secure card entry ready.");}}catch(e){if(active)setMessage(e instanceof Error?e.message:"Unable to initialize Square.");}})();return()=>{active=false;cardRef.current=null;if(card)void card.destroy().catch(()=>{});};},[]);
 async function submit(e:React.FormEvent){e.preventDefault();if(busy||!ready||!cardRef.current)return;const dollars=Number(amount.replace(/[$,\s]/g,""));const amountCents=Math.round(dollars*100);if(!Number.isFinite(dollars)||amountCents<1||Math.abs(dollars*100-amountCents)>.001){setMessage("Enter a valid amount with no more than two decimal places.");return;}if(!billing.first||!billing.last||!billing.address||!billing.city||!billing.state||!billing.zip){setMessage("Complete the billing name and address.");return;}setBusy(true);setMessage("Securely tokenizing card…");try{const tokenResult=await cardRef.current.tokenize({amount:(amountCents/100).toFixed(2),currencyCode:"USD",intent:"CHARGE",customerInitiated:true,sellerKeyedIn:true,billingContact:{givenName:billing.first,familyName:billing.last,email:billing.email||undefined,phone:billing.phone||undefined,addressLines:[billing.address],city:billing.city,state:billing.state,postalCode:billing.zip,countryCode:"US"}});if(tokenResult.status!=="OK"||!tokenResult.token){throw new Error(tokenResult.errors?.map((x:any)=>x.message||x.detail||x.type).filter(Boolean).join("; ")||"Card could not be tokenized.");}idemRef.current=idemRef.current||crypto.randomUUID();setMessage("Submitting payment…");await paymentDeskApi("charge",{method:"POST",body:{sourceId:tokenResult.token,amountCents,customerName:account.customer_name,reference,note,idempotencyKey:idemRef.current,crmAccountId:account.id,crmInstallmentId:nextInstallment?.id||null}});idemRef.current=null;setMessage("Payment approved.");try{await cardRef.current.clear();}catch{}await onComplete();}catch(e){if(e instanceof CrmApiError&&(e.data.transaction||e.data.squarePaymentId))idemRef.current=null;setMessage(e instanceof Error?e.message:"Payment was not completed.");}finally{setBusy(false);}}
 return <div className="crm-modal-backdrop"><form className="crm-modal crm-payment-form" onSubmit={submit}><div className="crm-row-between"><h2>Take Payment</h2><button type="button" onClick={onClose}>Close</button></div><div className="crm-payment-summary"><strong>{account.customer_name}</strong><span>Current balance {new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(account.currentBalanceCents/100)}</span></div><label>Payment amount<input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/></label><div className="crm-form-grid"><label>First name<input value={billing.first} onChange={e=>setBilling({...billing,first:e.target.value})}/></label><label>Last name<input value={billing.last} onChange={e=>setBilling({...billing,last:e.target.value})}/></label><label>Email<input type="email" value={billing.email} onChange={e=>setBilling({...billing,email:e.target.value})}/></label><label>Phone<input type="tel" value={billing.phone} onChange={e=>setBilling({...billing,phone:e.target.value})}/></label><label className="crm-full">Billing address<input value={billing.address} onChange={e=>setBilling({...billing,address:e.target.value})}/></label><label>City<input value={billing.city} onChange={e=>setBilling({...billing,city:e.target.value})}/></label><label>State<input value={billing.state} onChange={e=>setBilling({...billing,state:e.target.value})}/></label><label>ZIP<input inputMode="numeric" value={billing.zip} onChange={e=>setBilling({...billing,zip:e.target.value})}/></label></div><div id="crm-square-card" className="crm-square-card"/><label>Note<input value={note} onChange={e=>setNote(e.target.value)} placeholder="Optional"/></label><div className="crm-muted">{message}</div><button className="crm-primary" disabled={!ready||busy}>{busy?"Processing…":"Process Payment"}</button></form></div>;
}
