import { useMemo,useState } from "react";
import { paymentDeskApi } from "./crm-api";
import type { CrmAccount,CrmPlanBundle,CrmPaymentLink } from "./types";
const money=(c:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(c/100);
export function PaymentLinkPanel({account,plan,onClose,onComplete}:{account:CrmAccount;plan:CrmPlanBundle;onClose():void;onComplete():Promise<void>|void}){
 const next=plan.installments.find(i=>i.status!=="paid"&&i.status!=="waived");
 const [choice,setChoice]=useState<"full"|"next"|"custom">("full");const [custom,setCustom]=useState("");const [link,setLink]=useState<(CrmPaymentLink&{orderId?:string})|null>(null);const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
 const amountCents=useMemo(()=>choice==="full"?account.currentBalanceCents:choice==="next"?(next?Math.max(0,next.amount_due_cents-next.amount_paid_cents):0):Math.round(Number(custom||0)*100),[choice,custom,account.currentBalanceCents,next]);
 async function create(){if(!Number.isInteger(amountCents)||amountCents<1){setMessage("Enter a valid payment amount.");return;}setBusy(true);try{const r=await paymentDeskApi<{paymentLink:CrmPaymentLink&{orderId?:string}}>("create-payment-link",{method:"POST",body:{crmAccountId:account.id,crmInstallmentId:choice==="next"?next?.id:null,amountCents,idempotencyKey:crypto.randomUUID()}});setLink(r.paymentLink);setMessage("Secure Square payment link created.");}catch(e){setMessage(e instanceof Error?e.message:"Unable to create payment link.");}finally{setBusy(false);}}
 async function refresh(){if(!link)return;setBusy(true);try{const r=await paymentDeskApi<{paymentLink:CrmPaymentLink}>("refresh-payment-link",{method:"POST",body:{paymentLinkId:link.id}});setLink({...link,...r.paymentLink});setMessage(r.paymentLink.status==="paid"?"Payment received.":"No completed payment yet.");if(r.paymentLink.status==="paid")await onComplete();}catch(e){setMessage(e instanceof Error?e.message:"Unable to refresh payment link.");}finally{setBusy(false);}}
 async function copy(){if(!link)return;await navigator.clipboard.writeText(link.url);setMessage("Payment link copied.");}
 const smsMessage=link?`Therassistant: Here is your secure payment link for ${money(amountCents)}: ${link.url}`:"";
 const smsHref=link?`sms:${(account.phone||"").replace(/[^\d+]/g,"")}?body=${encodeURIComponent(smsMessage)}`:"#";
 return <div className="crm-modal-backdrop"><div className="crm-modal"><div className="crm-row-between"><h2>Text Payment Link</h2><button onClick={onClose}>Close</button></div><div className="crm-choice-grid"><label><input type="radio" checked={choice==="full"} onChange={()=>setChoice("full")}/> Full Balance <strong>{money(account.currentBalanceCents)}</strong></label><label><input type="radio" checked={choice==="next"} disabled={!next} onChange={()=>setChoice("next")}/> Next Installment {next&&<strong>{money(Math.max(0,next.amount_due_cents-next.amount_paid_cents))}</strong>}</label><label><input type="radio" checked={choice==="custom"} onChange={()=>setChoice("custom")}/> Custom Amount</label></div>{choice==="custom"&&<label>Amount<input inputMode="decimal" value={custom} onChange={e=>setCustom(e.target.value)}/></label>}{!link?<button className="crm-primary" disabled={busy} onClick={()=>void create()}>{busy?"Creating…":"Create Secure Payment Link"}</button>:<><div className="crm-link-box"><div className="crm-muted">Amount {money(amountCents)} · Status {link.status}</div><input readOnly value={link.url}/></div><div className="crm-form-actions"><button onClick={()=>void copy()}>Copy Link</button><a className="crm-button crm-primary" href={smsHref}>Text Payment Link</a><button disabled={busy} onClick={()=>void refresh()}>Refresh Status</button></div></>}<div className="crm-muted">{message}</div></div></div>;
}
