import { WorkDrawer } from "../../components/work-drawer";
import { StatusBadge } from "../../components/status-badge";
import { shortDate } from "../../lib/format";

type AuthorizationRecord = { id: string; patientId: string; patientName: string; payerName: string; authorizationNumber: string | null; status: string; endDate: string | null; remainingUnits: number | null; alert: string; needsAttention: boolean };
export function AuthorizationWorkDrawer({ record, open, onOpenChange }: { record: AuthorizationRecord | null; open: boolean; onOpenChange: (open: boolean) => void }) {
  return <WorkDrawer open={open} onOpenChange={onOpenChange} title={record?.patientName || "Authorization"} subtitle={record?.payerName || "Utilization management"} badges={record ? <StatusBadge value={record.status} /> : undefined} openFullRecord={record ? () => { window.location.href = `/clients/${record.patientId}`; } : undefined} openFullRecordLabel="Open Patient Chart">
    {!record ? <div className="thera-state">Select an authorization record.</div> : <div className="thera-stack"><section className="thera-card"><div className="thera-card-header"><div><h2>Authorization</h2><p>Review approval status, expiration, and available units without leaving the queue.</p></div></div><div className="thera-metric-grid"><div className="thera-metric-card"><div className="thera-metric-label">Authorization Number</div><div className="thera-metric-value small">{record.authorizationNumber || "Missing"}</div></div><div className="thera-metric-card"><div className="thera-metric-label">Status</div><div className="thera-metric-value small">{record.status}</div></div><div className="thera-metric-card"><div className="thera-metric-label">End Date</div><div className="thera-metric-value small">{record.endDate ? shortDate(record.endDate) : "—"}</div></div><div className="thera-metric-card"><div className="thera-metric-label">Units Remaining</div><div className="thera-metric-value small">{record.remainingUnits ?? "—"}</div></div></div></section>{record.needsAttention ? <section className="thera-card"><div className="thera-card-header"><h2>Needs Attention</h2></div><div className="thera-alert">Authorization alert: {record.alert}. Review the authorization before the next affected service is billed.</div></section> : null}</div>}
  </WorkDrawer>;
}
