import { WorkDrawer } from "../../components/work-drawer";
import { StatusBadge } from "../../components/status-badge";
import { shortDate } from "../../lib/format";

type EligibilityRecord = { id: string; patientId: string; patientName: string; payerName: string; memberId: string | null; serviceDate: string | null; status: string; needsAttention: boolean; policyId: string | null; payerId: string | null };
export function EligibilityWorkDrawer({ record, open, running, onOpenChange, onRun }: { record: EligibilityRecord | null; open: boolean; running: boolean; onOpenChange: (open: boolean) => void; onRun: () => void }) {
  return <WorkDrawer open={open} onOpenChange={onOpenChange} title={record?.patientName || "Eligibility"} subtitle={record?.payerName || "Coverage review"} badges={record ? <StatusBadge value={record.status} /> : undefined} openFullRecord={record ? () => { window.location.href = `/clients/${record.patientId}`; } : undefined} openFullRecordLabel="Open Patient Chart" footer={record ? <div className="thera-filter-row"><button type="button" className="thera-action" disabled={running || !record.policyId || !record.payerId || !record.memberId} onClick={onRun}>{running ? "Checking..." : "Run Eligibility"}</button></div> : undefined}>
    {!record ? <div className="thera-state">Select an eligibility record.</div> : <div className="thera-stack"><section className="thera-card"><h2>Coverage Status</h2><div className="thera-metric-grid"><div className="thera-metric-card"><div className="thera-metric-label">Patient</div><div className="thera-metric-value small">{record.patientName}</div></div><div className="thera-metric-card"><div className="thera-metric-label">Payer</div><div className="thera-metric-value small">{record.payerName}</div></div><div className="thera-metric-card"><div className="thera-metric-label">Member ID</div><div className="thera-metric-value small">{record.memberId || "Missing"}</div></div><div className="thera-metric-card"><div className="thera-metric-label">Latest DOS</div><div className="thera-metric-value small">{record.serviceDate ? shortDate(record.serviceDate) : "Not checked"}</div></div></div></section>{record.needsAttention ? <section className="thera-card"><h2>Needs Attention</h2><p>The latest coverage information requires review before relying on it for billing readiness.</p></section> : null}</div>}
  </WorkDrawer>;
}
