grant usage on schema public to anon;
grant select on public.tenants, public.payers to anon;
grant select, insert, update on public.clients, public.providers, public.provider_payer_enrollments, public.appointments, public.eligibility_checks, public.clinical_notes, public.charge_capture_items, public.professional_claims, public.workqueue_items, public.payments, public.denials to anon;

create policy "demo anon read tenants" on public.tenants for select to anon using ((settings->>'demo')::boolean is true);
create policy "demo anon read payers" on public.payers for select to anon using (true);

create policy "demo anon clients" on public.clients for all to anon using (exists (select 1 from public.tenants t where t.id = clients.tenant_id and (t.settings->>'demo')::boolean is true)) with check (exists (select 1 from public.tenants t where t.id = clients.tenant_id and (t.settings->>'demo')::boolean is true));
create policy "demo anon providers" on public.providers for all to anon using (exists (select 1 from public.tenants t where t.id = providers.tenant_id and (t.settings->>'demo')::boolean is true)) with check (exists (select 1 from public.tenants t where t.id = providers.tenant_id and (t.settings->>'demo')::boolean is true));
create policy "demo anon provider enrollments" on public.provider_payer_enrollments for all to anon using (exists (select 1 from public.tenants t where t.id = provider_payer_enrollments.tenant_id and (t.settings->>'demo')::boolean is true)) with check (exists (select 1 from public.tenants t where t.id = provider_payer_enrollments.tenant_id and (t.settings->>'demo')::boolean is true));
create policy "demo anon appointments" on public.appointments for all to anon using (exists (select 1 from public.tenants t where t.id = appointments.tenant_id and (t.settings->>'demo')::boolean is true)) with check (exists (select 1 from public.tenants t where t.id = appointments.tenant_id and (t.settings->>'demo')::boolean is true));
create policy "demo anon eligibility" on public.eligibility_checks for all to anon using (exists (select 1 from public.tenants t where t.id = eligibility_checks.tenant_id and (t.settings->>'demo')::boolean is true)) with check (exists (select 1 from public.tenants t where t.id = eligibility_checks.tenant_id and (t.settings->>'demo')::boolean is true));
create policy "demo anon clinical notes" on public.clinical_notes for all to anon using (exists (select 1 from public.tenants t where t.id = clinical_notes.tenant_id and (t.settings->>'demo')::boolean is true)) with check (exists (select 1 from public.tenants t where t.id = clinical_notes.tenant_id and (t.settings->>'demo')::boolean is true));
create policy "demo anon charges" on public.charge_capture_items for all to anon using (exists (select 1 from public.tenants t where t.id = charge_capture_items.tenant_id and (t.settings->>'demo')::boolean is true)) with check (exists (select 1 from public.tenants t where t.id = charge_capture_items.tenant_id and (t.settings->>'demo')::boolean is true));
create policy "demo anon claims" on public.professional_claims for all to anon using (exists (select 1 from public.tenants t where t.id = professional_claims.tenant_id and (t.settings->>'demo')::boolean is true)) with check (exists (select 1 from public.tenants t where t.id = professional_claims.tenant_id and (t.settings->>'demo')::boolean is true));
create policy "demo anon workqueues" on public.workqueue_items for all to anon using (exists (select 1 from public.tenants t where t.id = workqueue_items.tenant_id and (t.settings->>'demo')::boolean is true)) with check (exists (select 1 from public.tenants t where t.id = workqueue_items.tenant_id and (t.settings->>'demo')::boolean is true));
create policy "demo anon payments" on public.payments for all to anon using (exists (select 1 from public.tenants t where t.id = payments.tenant_id and (t.settings->>'demo')::boolean is true)) with check (exists (select 1 from public.tenants t where t.id = payments.tenant_id and (t.settings->>'demo')::boolean is true));
create policy "demo anon denials" on public.denials for all to anon using (exists (select 1 from public.tenants t where t.id = denials.tenant_id and (t.settings->>'demo')::boolean is true)) with check (exists (select 1 from public.tenants t where t.id = denials.tenant_id and (t.settings->>'demo')::boolean is true));
