-- Backfilled migration marker for a remote-applied credentialing migration.
-- Current credentialing index coverage is consolidated by the later
-- credentialing integrity synchronization migration in this branch.
